site_name: Linear Garage Door
repo_url: https://github.com/IceBotYT/linear-garage-door
repo_name: IceBotYT/linear-garage-door

theme:
  name: material
  features:
    - navigation.tracking
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: light blue
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: light blue
      accent: indigo

nav:
  - Introduction: 'index.md'
  - api_docs.md
  - changelog.md

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            show_source: false
            show_submodules: true

watch:
  - src/linear_garage_door
